### Numpy:- 
**NumPy(Numerical Python)** is a Python library used for scientific and numerical computing.

**Numpy:** is a fundamental library for scientific computing. It provides support for arrays and matrices along with a collection of mathematical functions to operate on this data. 

Key Points:

It provides a powerful object called ndarray (N-dimensional array).

It is much faster than Python lists for numerical operations.

It allows you to do mathematical, statistical, linear algebra, and logical operations easily.

Many data science and ML libraries (like pandas, scikit-learn, TensorFlow) are built on top of NumPy.

In [2]:
import numpy as np

#### Create array using numpy: 
#### Create 1D array

In [4]:
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [6]:
arr1.shape    #5 rows and 0 column

(5,)

#### Create 2D array:

In [8]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5)
print(type(arr2))

<class 'numpy.ndarray'>


In [9]:
arr3 = np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr3.shape)
print(arr3)

(2, 5)
[[1 2 3 4 5]
 [2 3 4 5 6]]


In [10]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [12]:
np.arange(0,10,2).reshape(5,1)    #5 rows and 1 column

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [15]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

#### Identity Matrix:-

In [18]:
np.eye(4)   #diagonal elements will be one.

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])