### Numpy:- 
**NumPy(Numerical Python)** is a Python library used for scientific and numerical computing.

**Numpy:** is a fundamental library for scientific computing. It provides support for arrays and matrices along with a collection of mathematical functions to operate on this data. 

Key Points:

It provides a powerful object called ndarray (N-dimensional array).

It is much faster than Python lists for numerical operations.

It allows you to do mathematical, statistical, linear algebra, and logical operations easily.

Many data science and ML libraries (like pandas, scikit-learn, TensorFlow) are built on top of NumPy.

In [2]:
import numpy as np

#### Create array using numpy: 
#### Create 1D array

In [4]:
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [6]:
arr1.shape    #5 rows and 0 column

(5,)

#### Create 2D array:

In [8]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5)
print(type(arr2))

<class 'numpy.ndarray'>


In [9]:
arr3 = np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr3.shape)
print(arr3)

(2, 5)
[[1 2 3 4 5]
 [2 3 4 5 6]]


In [10]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [12]:
np.arange(0,10,2).reshape(5,1)    #5 rows and 1 column

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [15]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

#### Identity Matrix:-

In [18]:
np.eye(4)   #diagonal elements will be one.

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [19]:
arr = np.array([[1,2,3],[4,5,6]])

print(f'Array: {arr}')
print(f'Shape: {arr.shape}')
print(f'Number of dimensions: {arr.ndim}')
print(f'Size of array: {arr.size}')
print(f'Array Data type: {arr.dtype}')
print(f'Item size(in bytes): {arr.itemsize}')

Array: [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size of array: 6
Array Data type: int64
Item size(in bytes): 8


#### Numpy Vectorize Operations:--

In [21]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

#### Elementwise addition, Substraction, Multiplication, Division:--

In [26]:
print(f'Addition: {arr1+arr2}')
print(f'Substraction: {arr1-arr2}')      
print(f'Multiplication: {arr1*arr2}')
print(f'Division: {arr1/arr2}')

Addition: [11 22 33 44 55]
Substraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


#### Universal Functions:- 

In [33]:
arr = np.array([2,3,4,5,6])

# square root
print(f'Square root: {np.sqrt(arr)}')
print(f'Exponential: {np.exp(arr)}')
print(f'Sine: {np.sin(arr)}')
print(f'Natural Log: {np.log(arr)}')

Square root: [1.41421356 1.73205081 2.         2.23606798 2.44948974]
Exponential: [  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
Sine: [ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
Natural Log: [0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


#### Array Slicing and Indexing:--

In [35]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print('Array: \n',arr)

Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [36]:
arr[0][0]

np.int64(1)

In [37]:
arr[0][3]


np.int64(4)

In [38]:
arr[0,3]   #This is concise way to access element.


np.int64(4)

In [39]:
arr[2,2]


np.int64(11)

In [40]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [41]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [44]:
arr[1:,1:3]

array([[ 6,  7],
       [10, 11]])

In [47]:
arr[0:2,1:3]

array([[2, 3],
       [6, 7]])